apiVersion: apps/v1
kind: Deployment
metadata:
  name: ClairvoyanceProMy
  labels:
    app: ClairvoyancePro
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: ClairvoyancePro
        service: webapp
    spec:
      containers:
        - name: ClairvoyanceProMy
          image: onefinsolution.azurecr.io/ClairvoyancePro:v15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: ClairvoyanceProMy
  labels:
    app: ClairvoyancePro
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp